import type { PlanConfig } from "@/lib/plans";

export const pricingPlans: PlanConfig[] = [
  {
    id: "free",
    name: "Free",
    price: 0,
    tagline: "For intimate celebrations",
    features: {
      rsvpLimit: 50,
      galleryLimit: 20,
      watermark: true,
      templateAccess: "starter",
      customTheme: false,
      guestbook: false,
      backgroundMusic: false,
      exportRsvp: false,
      customDomain: false,
      qrCheckIn: false,
    },
  },
  {
    id: "basic",
    name: "Basic",
    price: 149000,
    tagline: "Simple, elegant, ready",
    features: {
      rsvpLimit: 150,
      galleryLimit: 60,
      watermark: true,
      templateAccess: "classic",
      customTheme: false,
      guestbook: true,
      backgroundMusic: false,
      exportRsvp: false,
      customDomain: false,
      qrCheckIn: false,
    },
  },
  {
    id: "premium",
    name: "Premium",
    price: 299000,
    tagline: "Most-loved for full events",
    features: {
      rsvpLimit: 400,
      galleryLimit: 200,
      watermark: false,
      templateAccess: "premium",
      customTheme: true,
      guestbook: true,
      backgroundMusic: true,
      exportRsvp: true,
      customDomain: false,
      qrCheckIn: false,
    },
  },
  {
    id: "exclusive",
    name: "Exclusive",
    price: 599000,
    tagline: "Everything unlocked",
    features: {
      rsvpLimit: 1000,
      galleryLimit: 500,
      watermark: false,
      templateAccess: "all",
      customTheme: true,
      guestbook: true,
      backgroundMusic: true,
      exportRsvp: true,
      customDomain: true,
      qrCheckIn: true,
    },
  },
];
